fixed bug where arguments of a generic type did not work with choices and added typing_inspect.
Summary:
This was caused because issubclass can not be used with generic types:

https://docs.python.org/3/library/typing.html#typing.TypeVar
> At runtime, isinstance(x, T) will raise TypeError. In general, isinstance() and issubclass() should not be used with types.

```
: issubclass(typing.List[str], typing.List)
TypeError: Subscripted generics cannot be used with class and instance checks
```

Reviewed By: ylectric

Differential Revision: D19274547

fbshipit-source-id: 77e45e4341b84a05683e0bc2e742f148db217199